---
title: "functions"
author: "Matt Jones"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(roxygen2)
library(assertthat)
```

```{r}
airtemps <- c(212, 30.3, 78, 32, 0)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
celsius4 <- (airtemps[4]-32)*5/9
```

# Define conversion functions

First, F to C:

```{r}
#' Convert degrees Fahrenheit to Celsius
#'
#' We use the simpple formula for temperature conversion to convert.
#' One can find this in any intro Physics book.
#' @param fahr The temperature to be converted in degrees Fahrenheit
#' @return the temperature converted to degrees Celsius
#' @keywords conversion
#' @examples
#' fahr_to_celsisus(32)
#' fahr_to_celsisus(c(212, 100, 32))
fahr_to_celsius <- function(fahr) {
    #stopifnot(is.numeric(fahr))
    assert_that(is.numeric(fahr))
    celsius <- (fahr-32)*5/9
    return(celsius)
}
```

```{r}
celsius5 <- fahr_to_celsius(airtemps[1])
celsius5 == celsius1

celsius <- fahr_to_celsius(airtemps)
celsius
```

Now add a function for converting celsius to Fahrenheit.

```{r}
celsius_to_fahr <- function(celsius) {
    fahr <- (celsius*9/5) + 32
    return(fahr)
}
```

And test it.

```{r}
fahr <- celsius_to_fahr(celsius)
fahr == airtemps
```

